variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip
    - .npm/
    - .textlintcache

gitlint:
  image: python:3.7
  before_script:
    - pip install gitlint
  script:
    - gitlint

pre-commit:
  image: python:3.7
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

textlint:
  image: nikolaik/python-nodejs:python3.7-nodejs17-slim
  before_script:
    - pip install poetry
    - poetry install
    - npm ci --cache .npm --prefer-offline
  script:
    - poetry run task textlint
