#!/bin/bash

# This file is for Binder.
# https://mybinder.readthedocs.io/en/latest/using/config_files.html#start-run-code-before-the-user-sessions-starts

export LC_ALL=ja_JP.UTF-8
export LANG=ja_JP.UTF-8
export LANGUAGE=ja_JP.UTF-8
exec "$@"
