name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: deadsnakes/action@v3.2.0
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build
        if: ${{ github.ref_type != 'branch' || ! startsWith(github.ref_name, 'release') }}
        run: poetry run mkdocs build

      - name: Deploy
        if: ${{ github.ref_type == 'branch' && startsWith(github.ref_name, 'release') }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          poetry run mkdocs gh-deploy
