name: Lint

on: [push, pull_request]

jobs:
  gitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: deadsnakes/action@v3.2.0
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: pip install gitlint

      - name: Run gitlint
        run: gitlint

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: deadsnakes/action@v3.2.0
        with:
          python-version: '3.7'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  textlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: deadsnakes/action@v3.2.0
        with:
          python-version: '3.7'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: |
          poetry install --no-root
          npm install

      - name: textlint
        run: poetry run task textlint
